### ISSUE TITLE
Add slack as a target for Travis notifications

### ISSUE THREAD

**Issue by Temikus** [fog/fog-core#165]
We currently have Travis notifications pointing to IRC:
```
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
    - "[#%{build_number}] %{message} %{build_url}"
    - "[#%{build_number}] %{commit} on %{branch} by %{author}"
    - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false
```
With people now working in slack, it may make sense to push build notifications there as well.
It should be relatively simple to add:
http://docs.travis-ci.com/user/notifications/#Slack-notifications

/CC @plribeiro3000 as the slack org and fog-core owner, since I don't think I have access to generate API tokens.
